In [2]:
!pip install torch

  Using cached torch-2.2.2-cp312-none-macosx_10_9_x86_64.whl.metadata (25 kB)
  Using cached filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
  Using cached fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.2.2-cp312-none-macosx_10_9_x86_64.whl (150.8 MB)
Using cached filelock-3.17.0-py3-none-any.whl (16 kB)
Using cached fsspec-2025.2.0-py3-none-any.whl (184 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 6.7 MB/s eta 0:00:00a 0:00:01
Using cached sympy-1.13.3-py3-none-any.whl (6.2 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: pip install --upgrade pip


In [1]:
import torch
import torch.nn as nn

### Assign inputs to the neuron

In [2]:
inputs = torch.tensor([3.0,2.0,-1.0])

In [3]:
# Create a neuron with 3 features and 1 output. Here we use a linear activation function.
neuron = nn.Linear(in_features=3, out_features=1)
output = neuron(inputs)

In [4]:
print(output)

tensor([1.5484], grad_fn=<ViewBackward0>)


In [5]:
neuron.weight

Parameter containing:
tensor([[0.4522, 0.1168, 0.1347]], requires_grad=True)

In [6]:
neuron.bias

Parameter containing:
tensor([0.0931], requires_grad=True)

In [9]:
neuron.weight@inputs.T + neuron.bias

/var/folders/71/ymgjllnd4ps_ns5gg6w_0jnm0000gn/T/ipykernel_27104/576416303.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3641.)
  neuron.weight@inputs.T + neuron.bias


tensor([1.5484], grad_fn=<AddBackward0>)